Homework 1
================
Emily Bamforth

This is my solution for Homework 1.

``` r
library(tidyverse)
```

    ## ── Attaching packages ───────────────────── tidyverse 1.3.0 ──

    ## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.3     ✓ dplyr   1.0.2
    ## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
    ## ✓ readr   1.3.1     ✓ forcats 0.5.0

    ## ── Conflicts ──────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

#### Problem 1

**Creating data frame with specified elements:**

``` r
prob1_df =
  tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("low", "med", "high", "high", "low", "low",         "med", "high", "med", "med"))
  )
```

**Taking the mean of each variable:**

``` r
mean(pull(prob1_df, samp))
```

    ## [1] -0.3565413

``` r
mean(pull(prob1_df, samp_gt_0))
```

    ## [1] 0.3

``` r
mean(pull(prob1_df, char_vec))
```

    ## Warning in mean.default(pull(prob1_df, char_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(prob1_df, factor_vec))
```

    ## Warning in mean.default(pull(prob1_df, factor_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

**Findings:** We can take the mean of numbers and logical variables, but
not the mean of character or factor variables.

**Apply `as.numeric` function to the logical, character, and factor
variables.**

``` r
as.numeric(pull(prob1_df, samp_gt_0))
as.numeric(pull(prob1_df, char_vec))
as.numeric(pull(prob1_df, factor_vec))
```

**Findings:**

  - The logical variable is now numeric, with `TRUE` converted to 1 and
    `FALSE` converted to 0.

  - The character variable could not be converted to a numeric variable.
    A vector of NAs was returned.

  - The factor variable is now numeric, with `low` converted to 2,
    `medium` converted to 3, and `high` converted to 1.

  - This indicates that R can coerce logical variables into numeric when
    taking a mean. Even though it can convert factor variables into
    numeric, it does not coerce them into numeric to take a mean.

**Transforming some more variables:**

``` r
prob1_df %>% 
  pull(samp_gt_0) %>% 
  as.numeric() *
  pull(prob1_df, samp)
```

    ##  [1] 0.0000000 0.9641154 0.0000000 0.0000000 0.6325793 0.0000000 0.0000000
    ##  [8] 0.0000000 0.0000000 1.1580734

``` r
prob1_df %>% 
  pull(samp_gt_0) %>% 
  as.factor() *
  pull(prob1_df, samp)
```

    ## Warning in Ops.factor(prob1_df %>% pull(samp_gt_0) %>% as.factor(),
    ## pull(prob1_df, : '*' not meaningful for factors

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
prob1_df %>%
  pull(samp_gt_0) %>%
  as.factor() %>% 
  as.numeric() * 
  pull(prob1_df, samp)
```

    ##  [1] -0.6352604  1.9282309 -0.6361386 -0.4423244  1.2651587 -2.0432810
    ##  [7] -0.6402738 -1.8010136 -0.1218893  2.3161468

#### Problem 2

``` r
data("penguins", package = "palmerpenguins")
```

**Describing the dataset:**

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

This dataset has 344 rows and 8 columns.

  - Three factor variables: `species` `island` and `sex`

  - Three integer variables: `flipper_length_mm` `body_mass_g` and
    `year`

  - Two numeric variables: `bill_length_mm` and `bill_depth_mm`

<!-- end list -->

``` r
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

The data was collected between 2007 and 2009 across three islands:
Bisco, Dream and Torgersen.

There are three `species` represented: Adelie (n=152), Chinstrap (n=68),
and Gentoo (n=124).

**Practicing manually calculating means:**

The mean `body_mass_g` of the sample:

``` r
penguins %>% 
  pull(body_mass_g) %>%
  mean(na.rm = TRUE)
```

    ## [1] 4201.754

The mean `flipper_length_mm` of the sample:

``` r
penguins %>% 
  pull(flipper_length_mm) %>%
  mean(na.rm = TRUE)
```

    ## [1] 200.9152

The mean `bill_length_mm` of the sample:

``` r
penguins %>% 
  pull(bill_length_mm) %>%
  mean(na.rm = TRUE)
```

    ## [1] 43.92193
